#!/usr/bin/env bash

if [[ -d ".venv" ]]; then
  source .venv/bin/activate
else
  echo "Initialize virtualenv before running, see Makefile for more details."
  exit 1
fi

cd src && python rando-cli.py "$@"
