"""added bicycle class

Revision ID: 451cd345c9b6
Revises: e2d6573ec24c
Create Date: 2021-07-04 20:35:19.208527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '451cd345c9b6'
down_revision = 'e2d6573ec24c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bicycle',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('make', sa.Unicode(), nullable=True),
    sa.Column('model', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bicycle')
    # ### end Alembic commands ###
