"""initial generation

Revision ID: b4ff362dd0c0
Revises: 
Create Date: 2021-07-05 14:55:26.796030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4ff362dd0c0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bicycle',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('make', sa.Unicode(), nullable=True),
    sa.Column('model', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bicycle')
    # ### end Alembic commands ###
